app:
  build: ./
  volumes:
  - ./:/app
  - node_modules:/app/node_modules
  working_dir: /app
  command: npm run dev-docker
  links:
  - redis
  - mongo
  environment:
  - MONGODB=mongodb://mongo:27017/hackathon
  - REDIS=redis://redis:6379
  - VIRTUAL_HOST=obol.docker
mongo:
  image: mongo
redis:
  image: redis