app:
  build: ./
  volumes:
  - ./:/app
  working_dir: /app
  command: npm run dev-docker
  links:
  - redis
  - mongo
  environment:
  - MONGODB=mongodb://mongo:27017/obol
  - REDIS=redis://redis:6379
  - VIRTUAL_HOST=obol.docker
job:
  build: ./
  volumes:
  - ./:/app
  working_dir: /app
  command: npm run job
  links:
  - redis
  - mongo
  environment:
  - MONGODB=mongodb://mongo:27017/obol
  - REDIS=redis://redis:6379
  - VIRTUAL_HOST=obol.docker
mongo:
  image: mongo
redis:
  image: redis