app:
  build: ./
  links:
  - redis
  - mongo
  environment:
  - MONGODB=mongodb://mongo:27017/obol
  - REDIS=redis://redis:6379
  - VIRTUAL_HOST=obol.jlee.biz
  - NODE_ENV=production
job:
  build: ./
  command: npm run job
  links:
  - redis
  - mongo
  environment:
  - MONGODB=mongodb://mongo:27017/obol
  - REDIS=redis://redis:6379
  - VIRTUAL_HOST=obol.jlee.biz
  - NODE_ENV=production
mongo:
  image: mongo
redis:
  image: redis